version: '3.6'

services:
  bddmysql:
    container_name: "bddmysqlCrud"
    image: mysql:8
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pa
    volumes:
      - ./mysql:/var/lib/mysql